/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MultController;
import Main.GameManager;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.PrintWriter;
import javax.swing.JTextArea;

/**
 *
 * @author Arthur
 */
public class MultiplayerChat extends javax.swing.JFrame {

    private MultController controller;
    private String nome;
    private boolean host = false;
    
    /**
     * Creates new form MultiplayerChat
     */
    public MultiplayerChat() {
        initComponents();
        loadPrevius();
    }

    public void addController(MultController controller) {
        this.controller = controller;
    }
    
    public void conectado() {
        GameManager.getInstance().startMultGame();
        jBHost.setVisible(false);
        jBConectar.setVisible(false);
        String possivelNome = jTName.getText();
        jTName.setVisible(false);
        jTFIP.setVisible(false);
        if (possivelNome.length() < 1) {
            if(host)
                nome = "Host";
            else
                nome = "Cliente";
        }
        else
            nome = possivelNome;
        saveActual();
    }
    
    public JTextArea getTextArea() {
        return jTChat;
    }
    
    public MultController getController() {
        return controller;
    }
    
    public void loadPrevius() {
        try {
            FileInputStream f_in = new
                          FileInputStream ("data/credencial.data");
            BufferedReader s = new BufferedReader(new java.io.InputStreamReader(f_in));
            jTFIP.setText(s.readLine());
            jTName.setText(s.readLine());
            s.close();
        }
        catch (java.io.IOException e) {
        
        }
    }
    
    public void saveActual() {
        try {
            FileOutputStream arquivo = new 
                FileOutputStream("data/credencial.data");
            PrintStream saida = new PrintStream(arquivo);
            PrintWriter output = new PrintWriter(saida);
            output.println(jTFIP.getText());
            output.println(jTName.getText());
            output.flush();
            output.close();
        }
        catch (java.io.IOException e) {
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTChat = new javax.swing.JTextArea();
        jWrite = new javax.swing.JTextField();
        jTFIP = new javax.swing.JTextField();
        jBConectar = new javax.swing.JButton();
        jTName = new javax.swing.JTextField();
        jBHost = new javax.swing.JButton();
        jTPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTChat.setEditable(false);
        jTChat.setColumns(20);
        jTChat.setRows(5);
        jScrollPane1.setViewportView(jTChat);

        jWrite.setToolTipText("Diga o que quer");
        jWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWriteActionPerformed(evt);
            }
        });

        jTFIP.setText("127.0.0.1");
        jTFIP.setToolTipText("IP");
        jTFIP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIPActionPerformed(evt);
            }
        });

        jBConectar.setText("Conectar");
        jBConectar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarActionPerformed(evt);
            }
        });

        jTName.setToolTipText("Seu nome");
        jTName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jBHost.setText("Host");
        jBHost.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHostActionPerformed(evt);
            }
        });

        jTPort.setText("12345");
        jTPort.setToolTipText("Port");
        jTPort.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jWrite)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBHost, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBHost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFIP)
                        .addComponent(jTPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWrite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIPActionPerformed

    private void jBConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarActionPerformed
        // TODO add your handling code here:
        controller.conectar(jTFIP.getText(), jTPort.getText());
        
    }//GEN-LAST:event_jBConectarActionPerformed

    private void jBHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHostActionPerformed
        // TODO add your handling code here:
        controller.host(jTPort.getText());
        jBHost.setVisible(false);
        jBConectar.setVisible(false);
        host = true;
    }//GEN-LAST:event_jBHostActionPerformed

    private void jWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWriteActionPerformed
        // TODO add your handling code here:
        if(jWrite.getText().length() > 0) {
            GameManager.getInstance().log("Fala," + nome + "," + jWrite.getText());
            getTextArea().append(nome + ": " + jWrite.getText() + "\n");
            jWrite.setText("");
        }
    }//GEN-LAST:event_jWriteActionPerformed

    private void jTPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPortActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConectar;
    private javax.swing.JButton jBHost;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTChat;
    private javax.swing.JTextField jTFIP;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTPort;
    private javax.swing.JTextField jWrite;
    // End of variables declaration//GEN-END:variables
}
